### ISSUE TITLE
E10 Server spamming logs with same error constantly

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#161]
### Modpack Version

1.10.1

### Describe your issue.

everything in log is fine after server comes up but after it does come up it spams this every couple minutes

[09Oct2024 01:23:32.832] [Netty Epoll Server IO #1/WARN] [com.connectivity.Connectivity/]: Packet:ClientboundDisconnectPacket caused an error above, printing name & data
[09Oct2024 01:23:32.833] [Netty Epoll Server IO #1/WARN] [com.connectivity.Connectivity/]: Packet data:
"ClientboundDisconnectPacket[reason=translation{key='disconnect.genericReason', args=[Internal Exception: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer]}]"
[09Oct2024 01:23:32.833] [Netty Epoll Server IO #1/ERROR] [net.minecraft.network.PacketEncoder/]: Error sending packet clientbound/minecraft:disconnect
io.netty.handler.codec.EncoderException: Sending unknown packet 'clientbound/minecraft:disconnect'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:47) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:24) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.sendPacket(Connection.java:357) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.connectivity$wrapSend(Connection.java:756) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.redirect$zlh000$connectivity$logErrorFor(Connection.java:748) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.send(Connection.java:339) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.send(Connection.java:333) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.exceptionCaught(Connection.java:168) ~[server-1.21.1-20240808.144430-srg.jar%23313!/:?]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:826) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

DoomSquinter

**Comment by NielsPilgaard** [comment]
https://github.com/someaddons/connectivity/issues/104

**Comment by someaddons** [comment]
what that issue you're linking is describing is different, if you're interested in me fixing that bug please open a report on connectivity github issues with a proper log file

**Comment by DoomSquirter** [comment]
I had removed connectivity and it just changed the log file spamming but it still persisted.  

Either something is affecting both connectivity and another mod or the other mod is mostly if not all responsible for the spamming but who knows how to debug it.  

could even be a neoforge thing really.  I'm clueless tho.

**Comment by HeatherComputer** [comment]
Are you able to provide the changed logspam?

**Comment by someaddons** [comment]
if its happening without connectivity its not related to connectivity, as it does not change any data so removal is a clean slate. Logs would be indeed useful to find the issues, I always recommend putting the full log on https://gist.github.com/ :)

**Comment by DoomSquirter** [comment]
with connectivity
https://gist.github.com/DoomSquirter/e373668154d6d0a3ad1be489ee76243f
without connectivity
https://gist.github.com/DoomSquirter/15b7ab18a58dab4d17480eb6a4ac46fd

so, as I said, even w/o connectivity, the spam still happens.  no players need be on server or even attempt to login

so this is definately not a connectivity issue

**Comment by DoomSquirter** [comment]
turns out it was a bloom thing

For future reference, this is the setting (under setting on left) causing the issue

![Image](https://github.com/user-attachments/assets/dead7516-5c27-450b-b9d2-08894fce0782)
The second setting needs to be disabled
all it does is update how many players are online in the dashboard

**Comment by HeatherComputer** [comment]
now i have to wonder wtf bloom is doing there

**Comment by DoomSquirter** [comment]
it's nothing insidious.  it's like I said

![Image](https://github.com/user-attachments/assets/53763840-879a-4a48-b0c7-0786cef76a26)

![Image](https://github.com/user-attachments/assets/fc8ffd72-bbde-4212-a06d-7026d6c3c46d)

so, it's still a mod being culpable in this but there's no way we're going to probably find out which one

This is why I've run 3 or 4 other servers w/o this issue before this one w/o issue (with that option enabled)

**Comment by theboo** [comment]
in case anyone else runs in to this, the issue is with better compatibility checker. the same issue happens when using the craft4 server panelm disabling bcc makes all the logging go away. mod is safe to remove and clients with it can still connect

was reported over a year ago but the devs have not responded at all https://github.com/nanite/BetterCompatibilityChecker/issues/26
